id = "emmylua"
name = "EmmyLua"
description = "Advanced Lua language support with EmmyLua annotations, intelligent completions, powerful diagnostics and Debug Adapter Protocol support."
version = "0.21.0"
schema_version = 1
authors = ["0x2CA <2478557459@qq.com>", "CppCXY"]
repository = "https://github.com/EmmyLuaLs/Zed-EmmyLua"

[language_servers.emmylua]
name = "EmmyLua Language Server"
languages = ["EmmyLua", "Lua", "EmmyLuadoc"]

[debug_adapters.emmylua_new]
# EmmyLua Debug Adapter (emmylua_dap)
schema_path = "debug_adapter_schemas/emmylua_new.json"

[debug_locators.lua]
# Lua debug locator for converting run tasks to debug scenarios

[grammars.lua]
repository = "https://github.com/EmmyLuaLs/tree-sitter-lua"
commit = "dc39814f6ad5413cd52a9a4199395418601fbb6e"
[grammars.emmyluadoc]
repository = "https://github.com/EmmyLuaLs/tree-sitter-emmyluadoc"
commit = "ea755c0fd34c07e16597bd62a404d6eba2a3891e"
