on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Push events to matching vX.Y.Z

jobs:
  homebrew:
    name: Release Zed Extension
    runs-on: ubuntu-latest
    steps:
      - uses: huacnlee/zed-extension-action@v1
        with:
          extension-name: emmylua
          # extension-path: extensions/${{ extension-name }}
          push-to: EmmyLuaLs/zed-extensions
        env:
          # the personal access token should have "repo" & "workflow" scopes
          COMMITTER_TOKEN: ${{ secrets.RELEASE }}
